name: Test Action
# Run on PRs targeting main, and push to main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  # also support on workflow_dispatch
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Run a test of the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate test symbol file
        run: |
          cd .github/workflows
          clang --target=arm-none-eabi -nostdlib -Os -g1 -Wl,--entry=main,--build-id main.c -o test.elf
          readelf -n test.elf

      - name: Test action
        id: test_action
        uses: ./ # Uses an action in the root directory
        with:
          MEMFAULT_ORG_TOKEN: ${{ secrets.MEMFAULT_ORG_TOKEN }}
          MEMFAULT_ORG_SLUG: ${{ secrets.MEMFAULT_ORG_SLUG }}
          MEMFAULT_PROJECT_SLUG: ${{ secrets.MEMFAULT_PROJECT_SLUG }}
          symbol_file: .github/workflows/test.elf
